name: Keep Alive

on:
  schedule:
    # 10分毎に実行 (UTCで指定)
    - cron: '*/10 * * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Keep alive request
      run: |
        curl -f https://30s-english-news.onrender.com/health || echo "Health check failed"
        
    - name: Log status
      run: |
        echo "Keep alive ping sent at $(date)"